### ISSUE TITLE
Return all relationships from resource

### ISSUE THREAD

**Issue by jamesdb** [acredula/percy#37]
As title

I did it with:

```
$all = array_filter($include, function ($filter) {
    return (strtolower($filter === 'all'));
});

foreach ($this->getRelationshipMap() as $key => $map) {
    if (empty($all) && is_array($include) && ! in_array($key, $include)) {
        continue;
    }

    ...
}
```

This is not ideal due to the possibility of someone having a relationship called all.

**Comment by jamesdb** [comment]
You wot m8

**Comment by Maelstrome26** [comment]
Bit messy, but couldn't you have a query string such as `?all=true`?

**Comment by philipobenito** [comment]
Likely be handled with `/endpoint/resource?complete` not available on listings
